export const GET_BREEDS_SUCCESS = 'GET_BREEDS_SUCCESS';
export const GET_BREEDS_FAILURE = 'GET_BREEDS_FAILURE';
export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS';
export const GET_IMAGE_FAILURE = 'GET_IMAGE_FAILURE';